# Bitbucket pipelines configuration to run the tox tests
# (See https://confluence.atlassian.com/x/VYk8Lw)
image: ubuntu:18.04

pipelines:
  default:
    - step:
        script:
            - apt-get update
            - apt-get install -y apt-utils software-properties-common
            - add-apt-repository ppa:deadsnakes/ppa
            - apt-get update
            - apt-get install -y python3.4 python3.5 python3.6 python3.7 python3.8 virtualenv
            - python3 -m venv /opt/venv
            - /opt/venv/bin/pip install tox
            - /opt/venv/bin/tox
